export const assets = {
  hero: '/assets/hero/hero-bg.jpg',
  logo: '/assets/icons/logo.png',
  room: [
    '/assets/room/room-1.jpg',
    '/assets/room/room-2.jpg',
    '/assets/room/room-3.jpg',
    '/assets/room/room-4.jpg',
    '/assets/room/room-5.jpg',
    '/assets/room/room-6.jpg',
    '/assets/room/room-7.jpg',
    '/assets/room/room-8.jpg',
    '/assets/room/room-9.jpg',
    '/assets/room/room-10.jpg',
  ],
  gallery: [
    '/assets/gallery/gallery-1.jpg',
    '/assets/gallery/gallery-2.jpg',
    '/assets/gallery/gallery-3.jpg',
    '/assets/gallery/gallery-4.jpg',
    '/assets/gallery/gallery-5.jpg',
    '/assets/gallery/gallery-6.jpg',
    '/assets/gallery/gallery-7.jpg',
    '/assets/gallery/gallery-8.jpg',
    '/assets/gallery/gallery-9.jpg',
    '/assets/gallery/gallery-10.jpg',
    '/assets/gallery/gallery-11.png',
  ],
  icons: {
    shower: '/assets/icons/shower.png',
    balcony: '/assets/icons/balcony.png',
    bathtub: '/assets/icons/bathtub.png',
    steam: '/assets/icons/steam.png',
    garden: '/assets/icons/garden.png',
    desk: '/assets/icons/desk.png',
    wifi: '/assets/icons/wifi.png',
    ac: '/assets/icons/ac.png',
    minibar: '/assets/icons/minibar.png',
    safe: '/assets/icons/safe.png',
    visibility: '/assets/icons/visibility.png',
    cutlery: '/assets/icons/cutlery.png',
    solidarity: '/assets/icons/solidarity.png',
    activity: '/assets/icons/activity.png',
    arrival: '/assets/icons/arrival.png',
    departure: '/assets/icons/departure.png',
    breakfast: '/assets/icons/breakfast.png',
    halfboard: '/assets/icons/halfboard.png',
    shuttle: '/assets/icons/shuttle.png',
    lateCheckout: '/assets/icons/late-checkout.png',
    crib: '/assets/icons/crib.png',
  },
  ui: {
    toggleOn: '/assets/ui/toggle-on.svg',
    calendar: '/assets/ui/calendar.png',
    checkbox: '/assets/ui/checkbox.svg',
    arrowDownWhite: '/assets/ui/arrow-down-white.svg',
    arrowDown: '/assets/ui/arrow-down.svg',
  },
} as const;
